INSERT INTO ACTIVITY_RELATION (ACTIVITY_1_ID, ACTIVITY_2_ID, OWNER_ID) VALUES (3, 1, 1);
INSERT INTO ACTIVITY_RELATION (ACTIVITY_1_ID, ACTIVITY_2_ID, OWNER_ID) VALUES (3, 2, 1);
INSERT INTO ACTIVITY_RELATION (ACTIVITY_1_ID, ACTIVITY_2_ID, OWNER_ID) VALUES (3, 4, 2);
INSERT INTO ACTIVITY_RELATION (ACTIVITY_1_ID, ACTIVITY_2_ID, OWNER_ID) VALUES (4, 2, 2);
INSERT INTO ACTIVITY_RELATION (ACTIVITY_1_ID, ACTIVITY_2_ID, OWNER_ID) VALUES (4, 3, 2);

INSERT INTO ACTIVITY_RATING (ACTIVITY_ID, USER_ID, RATING, FAVOURITE) VALUES (1, 1, 3, TRUE);
INSERT INTO ACTIVITY_RATING (ACTIVITY_ID, USER_ID, RATING, FAVOURITE) VALUES (1, 2, 4, FALSE);
INSERT INTO ACTIVITY_RATING (ACTIVITY_ID, USER_ID, RATING, FAVOURITE) VALUES (2, 1, 4, FALSE);
INSERT INTO ACTIVITY_RATING (ACTIVITY_ID, USER_ID, RATING, FAVOURITE) VALUES (2, 2, 5, FALSE);
INSERT INTO ACTIVITY_RATING (ACTIVITY_ID, USER_ID, RATING, FAVOURITE) VALUES (3, 1, 5, FALSE);
