INSERT INTO ACTIVITY_RATING (ACTIVITY_ID, USER_ID, RATING, FAVOURITE) VALUES (1, 1, 3, FALSE);
INSERT INTO ACTIVITY_RATING (ACTIVITY_ID, USER_ID, RATING, FAVOURITE) VALUES (1, 2, 4, TRUE);
INSERT INTO ACTIVITY_RATING (ACTIVITY_ID, USER_ID, RATING, FAVOURITE) VALUES (2, 1, 4, FALSE);
INSERT INTO ACTIVITY_RATING (ACTIVITY_ID, USER_ID, RATING, FAVOURITE) VALUES (2, 2, 5, FALSE);
INSERT INTO ACTIVITY_RATING (ACTIVITY_ID, USER_ID, RATING, FAVOURITE) VALUES (3, 1, 5, FALSE);
