ALTER TABLE UTBETALING_BEGRUNNELSE
    RENAME TO VEDTAK_BEGRUNNELSE;
ALTER SEQUENCE UTBETALING_BEGRUNNELSE_SEQ RENAME TO VEDTAK_BEGRUNNELSE_SEQ;

ALTER TABLE VEDTAK_BEGRUNNELSE
    RENAME COLUMN VEDTAK_BEGRUNNELSE TO BEGRUNNELSE;

ALTER TABLE VEDTAK_BEGRUNNELSE
    DROP COLUMN BEGRUNNELSE_TYPE;