ALTER TABLE SAKSSTATISTIKK_MELLOMLAGRING ADD COLUMN SENDT_TID TIMESTAMP(3) DEFAULT LOCALTIMESTAMP;
ALTER TABLE SAKSSTATISTIKK_MELLOMLAGRING ADD COLUMN TYPE_ID BIGINT;

ALTER TABLE SAKSSTATISTIKK_MELLOMLAGRING ALTER COLUMN OFFSET_VERDI DROP NOT NULL;