UPDATE vedtak_begrunnelse SET begrunnelse='ENDRET_OG_FORTSATT_INNVILGET' WHERE begrunnelse='REDUKSJON_FLYTTET_FORELDER';
UPDATE vedtak_begrunnelse SET begrunnelse='OPPHØR_BARN_FLYTTET_FRA_SØKER' WHERE begrunnelse='OPPHØR_SØKER_FLYTTET_FRA_BARN';
UPDATE vedtak_begrunnelse SET begrunnelse='FORTSATT_INNVILGET_SØKER_BOSATT_I_RIKET' WHERE begrunnelse='FORTSATT_INNVILGET_TEST';