CREATE TABLE GR_PERIODE_OVERGANGSSTONAD
(
    ID               BIGINT PRIMARY KEY,
    FK_BEHANDLING_ID BIGINT REFERENCES BEHANDLING (ID)   NOT NULL,
    PERSON_IDENT     VARCHAR                             NOT NULL,
    FOM              TIMESTAMP(3)                        NOT NULL,
    TOM              TIMESTAMP(3)                        NOT NULL,
    DATAKILDE        VARCHAR                             NOT NULL,
    VERSJON          BIGINT       DEFAULT 0              NOT NULL,
    OPPRETTET_AV     VARCHAR      DEFAULT 'VL'           NOT NULL,
    OPPRETTET_TID    TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
    ENDRET_AV        VARCHAR,
    ENDRET_TID       TIMESTAMP(3)
);

CREATE SEQUENCE GR_PERIODE_OVERGANGSSTONAD_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE INDEX ON GR_PERIODE_OVERGANGSSTONAD (FK_BEHANDLING_ID);

