CREATE TABLE BATCH
(
    ID          BIGINT PRIMARY KEY,
    KJOREDATO   TIMESTAMP(3) NOT NULL,
    STATUS      VARCHAR(50) NOT NULL DEFAULT 'LEDIG'
);

CREATE SEQUENCE BATCH_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;