CREATE TABLE SKYGGESAK
(
    ID           BIGINT NOT NULL PRIMARY KEY,
    FK_FAGSAK_ID BIGINT NOT NULL,
    SENDT_TID    TIMESTAMP(3)
);

CREATE SEQUENCE SKYGGESAK_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE INDEX skyggesak_fagsak_id_idx ON skyggesak (fk_fagsak_id);