CREATE TABLE BEHANDLING_SOKNADSINFO
(
    ID               BIGINT PRIMARY KEY,
    FK_BEHANDLING_ID BIGINT REFERENCES BEHANDLING (ID)   NOT NULL,
    MOTTATT_DATO     TIMESTAMP(3)                        NOT NULL,
    VERSJON          BIGINT       DEFAULT 0              NOT NULL,
    OPPRETTET_AV     VARCHAR      DEFAULT 'VL'           NOT NULL,
    OPPRETTET_TID    TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
    ENDRET_AV        VARCHAR,
    ENDRET_TID       TIMESTAMP(3)
);

CREATE SEQUENCE BEHANDLING_SOKNADSINFO_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE INDEX ON BEHANDLING_SOKNADSINFO (FK_BEHANDLING_ID);