CREATE TABLE KOMPETANSE
(
    ID               BIGINT PRIMARY KEY,
    FK_BEHANDLING_ID BIGINT REFERENCES BEHANDLING (ID)   NOT NULL,
    FOM              TIMESTAMP(3),
    TOM              TIMESTAMP(3),
    VERSJON          BIGINT       DEFAULT 0              NOT NULL,
    OPPRETTET_AV     VARCHAR      DEFAULT 'VL'           NOT NULL,
    OPPRETTET_TID    TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
    ENDRET_AV        VARCHAR,
    ENDRET_TID       TIMESTAMP(3)
);

CREATE SEQUENCE KOMPETANSE_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE INDEX KOMPETANSE_FK_BEHANDLING_ID_IDX ON KOMPETANSE (FK_BEHANDLING_ID);

CREATE TABLE AKTOER_TIL_KOMPETANSE
(
    FK_KOMPETANSE_ID BIGINT REFERENCES KOMPETANSE (ID)     NOT NULL,
    FK_AKTOER_ID     VARCHAR REFERENCES AKTOER (AKTOER_ID) NOT NULL,
    PRIMARY KEY (FK_KOMPETANSE_ID, FK_AKTOER_ID)
);