CREATE TABLE VALUTAKURS
(
    ID               BIGINT PRIMARY KEY,
    FK_BEHANDLING_ID BIGINT REFERENCES BEHANDLING (ID)   NOT NULL,
    FOM              TIMESTAMP(3),
    TOM              TIMESTAMP(3),
    VALUTAKURSDATO   TIMESTAMP(3) DEFAULT null,
    VALUTAKODE       VARCHAR      DEFAULT null,
    KURS             DECIMAL      DEFAULT null,
    VERSJON          BIGINT       DEFAULT 0              NOT NULL,
    OPPRETTET_AV     VARCHAR      DEFAULT 'VL'           NOT NULL,
    OPPRETTET_TID    TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
    ENDRET_AV        VARCHAR,
    ENDRET_TID       TIMESTAMP(3)
);

CREATE SEQUENCE VALUTAKURS_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE INDEX VALUTAKURS_FK_BEHANDLING_ID_IDX ON VALUTAKURS (FK_BEHANDLING_ID);

CREATE TABLE AKTOER_TIL_VALUTAKURS
(
    FK_VALUTAKURS_ID BIGINT REFERENCES VALUTAKURS (ID)     NOT NULL,
    FK_AKTOER_ID     VARCHAR REFERENCES AKTOER (AKTOER_ID) NOT NULL,
    PRIMARY KEY (FK_VALUTAKURS_ID, FK_AKTOER_ID)
);