CREATE TABLE UTENLANDSK_PERIODEBELOEP
(
    ID               BIGINT PRIMARY KEY,
    FK_BEHANDLING_ID BIGINT REFERENCES BEHANDLING (ID)   NOT NULL,
    FOM              TIMESTAMP(3),
    TOM              TIMESTAMP(3),
    INTERVALL        VARCHAR      DEFAULT null,
    VALUTAKODE       VARCHAR      DEFAULT null,
    BELOEP           DECIMAL      DEFAULT null,
    VERSJON          BIGINT       DEFAULT 0              NOT NULL,
    OPPRETTET_AV     VARCHAR      DEFAULT 'VL'           NOT NULL,
    OPPRETTET_TID    TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
    ENDRET_AV        VARCHAR,
    ENDRET_TID       TIMESTAMP(3)
);

CREATE SEQUENCE UTENLANDSK_PERIODEBELOEP_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE INDEX UTENLANDSK_PERIODEBELOEP_FK_BEHANDLING_ID_IDX ON UTENLANDSK_PERIODEBELOEP (FK_BEHANDLING_ID);

CREATE TABLE AKTOER_TIL_UTENLANDSK_PERIODEBELOEP
(
    FK_UTENLANDSK_PERIODEBELOEP_ID BIGINT REFERENCES UTENLANDSK_PERIODEBELOEP (ID) NOT NULL,
    FK_AKTOER_ID                   VARCHAR REFERENCES AKTOER (AKTOER_ID)           NOT NULL,
    PRIMARY KEY (FK_UTENLANDSK_PERIODEBELOEP_ID, FK_AKTOER_ID)
);