CREATE TABLE KORRIGERT_VEDTAK
(
    ID               BIGINT PRIMARY KEY,
    BEGRUNNELSE      VARCHAR,
    VEDTAKSDATO      TIMESTAMP(3) DEFAULT null,
    AKTIV            BOOLEAN                             NOT NULL,
    FK_BEHANDLING_ID BIGINT REFERENCES BEHANDLING (ID)   NOT NULL,

    -- Base entitet felter
    VERSJON          BIGINT       DEFAULT 0              NOT NULL,
    OPPRETTET_AV     VARCHAR      DEFAULT 'VL'           NOT NULL,
    OPPRETTET_TID    TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
    ENDRET_AV        VARCHAR,
    ENDRET_TID       TIMESTAMP(3)
);

CREATE SEQUENCE korrigert_vedtak_seq INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE UNIQUE INDEX UIDX_KORRIGERT_VEDTAK_FK_BEHANDLING_ID_AKTIV ON KORRIGERT_VEDTAK (FK_BEHANDLING_ID) where AKTIV=true;
CREATE INDEX on KORRIGERT_VEDTAK (fk_behandling_id);
