CREATE TABLE TREKK_I_LOEPENDE_UTBETALING
(
    ID                  BIGINT PRIMARY KEY,
    FK_BEHANDLING_ID    BIGINT REFERENCES BEHANDLING (ID)   NOT NULL,
    FOM                 TIMESTAMP(3),
    TOM                 TIMESTAMP(3),
    FEILUTBETALT_BELOEP NUMERIC,
    VERSJON             BIGINT       DEFAULT 0              NOT NULL,
    OPPRETTET_AV        VARCHAR      DEFAULT 'VL'           NOT NULL,
    OPPRETTET_TID       TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
    ENDRET_AV           VARCHAR,
    ENDRET_TID          TIMESTAMP(3)
);

CREATE SEQUENCE TREKK_I_LOEPENDE_UTBETALING_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE INDEX TREKK_I_LOEPENDE_UTBETALING_FK_BEHANDLING_ID_IDX ON TREKK_I_LOEPENDE_UTBETALING (FK_BEHANDLING_ID);