ALTER TABLE TREKK_I_LOEPENDE_UTBETALING
    RENAME TO FEILUTBETALT_VALUTA;

ALTER SEQUENCE TREKK_I_LOEPENDE_UTBETALING_SEQ
    RENAME TO FEILUTBETALT_VALUTA_SEQ;

ALTER INDEX TREKK_I_LOEPENDE_UTBETALING_FK_BEHANDLING_ID_IDX
    RENAME TO FEILUTBETALT_VALUTA_FK_BEHANDLING_ID_IDX;