CREATE TABLE REFUSJON_EOS
(
    ID               BIGINT PRIMARY KEY,
    FK_BEHANDLING_ID BIGINT REFERENCES BEHANDLING (ID)   NOT NULL,
    FOM              TIMESTAMP(3)                        NOT NULL,
    TOM              TIMESTAMP(3)                        NOT NULL,
    REFUSJONSBELOEP  NUMERIC                             NOT NULL,
    LAND             VARCHAR                             NOT NULL,
    REFUSJON_AVKLART BOOLEAN                             NOT NULL,
    VERSJON          BIGINT       DEFAULT 0              NOT NULL,
    OPPRETTET_AV     VARCHAR      DEFAULT 'VL'           NOT NULL,
    OPPRETTET_TID    TIMESTAMP(3) DEFAULT localtimestamp NOT NULL,
    ENDRET_AV        VARCHAR,
    ENDRET_TID       TIMESTAMP(3)
);

CREATE SEQUENCE REFUSJON_EOS_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE INDEX REFUSJON_EOS_FK_BEHANDLING_ID_IDX ON REFUSJON_EOS (FK_BEHANDLING_ID);
