DROP INDEX IF EXISTS vilkar_resultat_fk_idx;

ALTER TABLE VILKAR_RESULTAT
DROP CONSTRAINT IF EXISTS FK_BEHANDLING_ID_VILKAR_RESULTAT;

ALTER TABLE VILKAR_RESULTAT
    RENAME COLUMN FK_BEHANDLING_ID TO SIST_ENDRET_I_BEHANDLING_ID;

ALTER TABLE VILKAR_RESULTAT
ADD CONSTRAINT SIST_ENDRET_I_BEHANDLING_ID_VILKAR_RESULTAT FOREIGN KEY (SIST_ENDRET_I_BEHANDLING_ID) REFERENCES BEHANDLING (ID);

CREATE INDEX ON VILKAR_RESULTAT(SIST_ENDRET_I_BEHANDLING_ID);