CREATE TABLE SATS (
    ID BIGINT PRIMARY KEY,
    TYPE VARCHAR(100) NOT NULL,
    BELOP BIGINT NOT NULL,
    GYLDIG_FOM TIMESTAMP,
    GYLDIG_TOM TIMESTAMP
);

CREATE SEQUENCE SATS_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;

INSERT INTO SATS (id, type, belop, gyldig_fom) VALUES (1, 'ORBA', 1054, to_date('01-03-2019', 'DD-MM-YYYY')) ON CONFLICT DO NOTHING;
INSERT INTO SATS (id, type, belop, gyldig_tom) VALUES (2, 'ORBA', 970, to_date('28-02-2019', 'DD-MM-YYYY')) ON CONFLICT DO NOTHING;
INSERT INTO SATS (id, type, belop) VALUES (3, 'SMA', 660) ON CONFLICT DO NOTHING;
INSERT INTO SATS (id, type, belop, gyldig_fom) VALUES (4, 'TILLEGG_ORBA', 1354, to_date('01-09-2020', 'DD-MM-YYYY')) ON CONFLICT DO NOTHING;
INSERT INTO SATS (id, type, belop, gyldig_tom) VALUES (5, 'FINN_SVAL', 1054, to_date('31-03-2014', 'DD-MM-YYYY')) ON CONFLICT DO NOTHING;
