CREATE TABLE FAGSAK_PERSON (
    ID            BIGINT        PRIMARY KEY,
    FK_FAGSAK_ID     BIGINT        NOT NULL,
    IDENT         VARCHAR(50)   NOT NULL,
    OPPRETTET_AV  VARCHAR(512)   DEFAULT 'VL',
    OPPRETTET_TID TIMESTAMP(3)  DEFAULT localtimestamp
);
CREATE SEQUENCE FAGSAK_PERSON_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
create index on FAGSAK_PERSON (FK_FAGSAK_ID);
create index on FAGSAK_PERSON (IDENT);
