INSERT INTO FAGSAK_PERSON (ID, FK_FAGSAK_ID, IDENT, OPPRETTET_AV, OPPRETTET_TID)
SELECT nextval('FAGSAK_PERSON_SEQ'), ID, PERSON_IDENT, OPPRETTET_AV, OPPRETTET_TID FROM FAGSAK;

ALTER TABLE fagsak ALTER COLUMN person_ident DROP NOT NULL;
ALTER TABLE fagsak ALTER COLUMN aktoer_id DROP NOT NULL;