CREATE TABLE JOURNALPOST
(
    ID               BIGINT PRIMARY KEY,
    FK_BEHANDLING_ID BIGINT REFERENCES BEHANDLING (id) NOT NULL,
    JOURNALPOST_ID   VARCHAR                           NOT NULL
);

CREATE SEQUENCE JOURNALPOST_SEQ INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE INDEX ON JOURNALPOST (FK_BEHANDLING_ID);

INSERT INTO JOURNALPOST(id, FK_BEHANDLING_ID, JOURNALPOST_ID)
SELECT nextval('JOURNALPOST_SEQ'), B.id, B.journalpost_id FROM BEHANDLING B
WHERE journalpost_id IS NOT NULL;