ALTER TABLE VILKAR_RESULTAT
RENAME COLUMN BEHANDLING_ID TO FK_BEHANDLING_ID;

ALTER TABLE VILKAR_RESULTAT
ADD CONSTRAINT FK_BEHANDLING_ID_VILKAR_RESULTAT FOREIGN KEY (FK_BEHANDLING_ID) REFERENCES BEHANDLING (ID);