ALTER TABLE UTBETALING_BEGRUNNELSE
    ADD COLUMN OPPRETTET_AV VARCHAR DEFAULT 'VL' NOT NULL;

ALTER TABLE UTBETALING_BEGRUNNELSE
    ADD COLUMN OPPRETTET_TID TIMESTAMP(3) DEFAULT LOCALTIMESTAMP NOT NULL;

ALTER TABLE UTBETALING_BEGRUNNELSE
    ADD COLUMN ENDRET_AV VARCHAR;

ALTER TABLE UTBETALING_BEGRUNNELSE
    ADD COLUMN ENDRET_TID TIMESTAMP(3);

ALTER TABLE UTBETALING_BEGRUNNELSE
    ADD COLUMN VERSJON BIGINT DEFAULT 0 NOT NULL;
