UPDATE VILKAR_RESULTAT
SET resultat = 'OPPFYLT'
WHERE resultat = 'JA';

UPDATE VILKAR_RESULTAT
SET resultat = 'IKKE_OPPFYLT'
WHERE resultat = 'NEI';

UPDATE VILKAR_RESULTAT
SET resultat = 'IKKE_VURDERT'
WHERE resultat = 'KANSKJE';