-- adds ROLE_USER to all users that still don't have it
INSERT INTO APP.PERSON_ROLES (
  PERSON_ID,
  ROLES_ID
)
SELECT ID,
(SELECT ID FROM APP.ROLE WHERE AUTHORITY='ROLE_USER')
FROM APP.PERSON
WHERE ID NOT IN (
  SELECT pr.PERSON_ID
  FROM APP.PERSON_ROLES pr, APP.ROLE r
  WHERE pr.ROLES_ID=r.ID
  AND r.AUTHORITY='ROLE_USER'
);
