package no.nav.tag.tiltaksgjennomforing.avtale;

public enum AvtaleInnholdType {
    INNGÅ, LÅSE_OPP, FORLENGE, FORKORTE, ENDRE_MÅL, ENDRE_INKLUDERINGSTILSKUDD, ENDRE_OM_MENTOR, ENDRE_TILSKUDDSBEREGNING, ENDRE_STILLING, ENDRE_KONTAKTINFO, ENDRE_OPPFØLGING_OG_TILRETTELEGGING, ANNULLERE
}
