#!/bin/bash

# Credits: https://github.com/shekhargulati/spark-openshift-quickstart/blob/master/.openshift/action_hooks/deploy
# Credits: http://www.hfaber.com/post/135193402529/jdk-8-support-at-diy-cartridge-in-openshift

# First download Maven if it is missing (own installation required for Java 8 support). A similar mechanism should be
# added for downloading Java 8 (which is why we need our own Maven installation in the first place).

if [ ! -d $OPENSHIFT_DATA_DIR/apache-maven-3.3.3 ]
	then
		echo Downloading Maven
		cd $OPENSHIFT_DATA_DIR
		wget http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
		tar xvf apache-maven-3.3.3-bin.tar.gz
		rm -f apache-maven-3.3.3-bin.tar.gz
fi

# Export paths in order to make Maven support Java 8:

export M2=$OPENSHIFT_DATA_DIR/apache-maven-3.3.3/bin
export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk1.8.0_05"
export PATH=$JAVA_HOME/bin:$M2:$PATH

cd $OPENSHIFT_REPO_DIR

#
# BUILD
#
# Note: skip tests because they take a lot of time to execute
#

echo Building application

mvn -s $OPENSHIFT_REPO_DIR/.openshift/settings.xml -Dmaven.test.skip=true clean package

echo Build script done.