services:
  mitmproxy:
    image: mitmproxy/mitmproxy:10.2.4
    user: "0:0"
    environment:
      MITM_LOG_DIR: /custom-logs
      MITM_LOG_FILE: ${MITM_LOG_FILE:-minlog.csv}
    command: >
      mitmdump 
        --mode reverse:http://sut-catwatch:8080
        --listen-host 0.0.0.0
        --listen-port 8080
        --set keep_host_header=true
        -s /addons/minlog.py
    volumes:
      - ${HOST_LOG_DIR:-./mitm-logs}:/custom-logs
      - ./addons:/addons:ro
    ports:
      - "${HOST_PORT:-8080}:8080"
    depends_on:
      - sut-catwatch
  sut-catwatch:
    image: webfuzzing/wfd-catwatch:FINAL
#    build:
#      dockerfile: ./dockerfiles/catwatch.dockerfile
#      context: ..
    environment:
       AUTH_PORT: ${AUTH_PORT:-8081}
    ports:
      - "${JACOCO_PORT:-6300}:6300"