services:
  mitmproxy:
    image: mitmproxy/mitmproxy:10.2.4
    user: "0:0"
    environment:
      MITM_LOG_DIR: /custom-logs
      MITM_LOG_FILE: ${MITM_LOG_FILE:-minlog.csv}
    command: >
      mitmdump 
        --mode reverse:http://sut-reservations-api:8080
        --listen-host 0.0.0.0
        --listen-port 8080
        --set keep_host_header=true
        -s /addons/minlog.py
    volumes:
      - ${HOST_LOG_DIR:-./mitm-logs}:/custom-logs
      - ./addons:/addons:ro
    ports:
      - "${HOST_PORT:-8080}:8080"
    depends_on:
      - sut-reservations-api
  sut-reservations-api:
    image: webfuzzing/wfd-reservations-api:FINAL
#    build:
#      dockerfile: ./dockerfiles/reservations-api.dockerfile
#      context: ..
    environment:
       AUTH_PORT: ${AUTH_PORT:-8081}
    ports:
      - "${JACOCO_PORT:-6300}:6300"
  db:
    image: mongo:4.4
    tmpfs:
      - '/data/db'
    volumes:
      - ./additional_files/reservations-api/mongo-init.js:/docker-entrypoint-initdb.d/01-init-replica.js
      - ./additional_files/reservations-api/mongo_import.sh:/docker-entrypoint-initdb.d/mongo_import.sh
      - ./additional_files/reservations-api/init.json:/fixtures/init.json
    command: mongod --replSet rs0 --bind_ip_all