services:
  mitmproxy:
    image: mitmproxy/mitmproxy:10.2.4
    user: "0:0"
    environment:
      MITM_LOG_DIR: /custom-logs
      MITM_LOG_FILE: ${MITM_LOG_FILE:-minlog.csv}
    command: >
      mitmdump 
        --mode reverse:http://sut-spring-ecommerce:8080
        --listen-host 0.0.0.0
        --listen-port 8080
        --set keep_host_header=true
        -s /addons/minlog.py
    volumes:
      - ${HOST_LOG_DIR:-./mitm-logs}:/custom-logs
      - ./addons:/addons:ro
    ports:
      - "${HOST_PORT:-8080}:8080"
    depends_on:
      - sut-spring-ecommerce
  sut-spring-ecommerce:
    image: webfuzzing/wfd-spring-ecommerce:FINAL
#    build:
#      dockerfile: ./dockerfiles/spring-ecommerce.dockerfile
#      context: ..
    environment:
       AUTH_PORT: ${AUTH_PORT:-8081}
    ports:
      - "${JACOCO_PORT:-6300}:6300"
  mongodb:
    image: mongo:7.0
    tmpfs:
      - '/data/db'
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./additional_files/spring-ecommerce/mongo_import.sh:/docker-entrypoint-initdb.d/mongo_import.sh
      - ./additional_files/spring-ecommerce/init.json:/fixtures/init.json
  redis:
    image: redis:7.0.11
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    tmpfs:
      - '/usr/share/elasticsearch/data'
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false